name: skin_disease_app
description: "A Flutter project to scan skin diseases using Google Vision API."

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  http: ^0.13.6
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^9.1.1
  form_builder_validators: 11.1.2
  geolocator: ^10.1.0
  url_launcher: ^6.2.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/appicon.png"

flutter:
  uses-material-design: true

  assets:
    - .env
